/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as CoreRouteImport } from './routes/core'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IslaRouteImport } from './routes/isla'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PersonalizeRouteImport } from './routes/personalize'
import { Route as WorldRouteImport } from './routes/world'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IslaRoute = IslaRouteImport.update({
  id: '/isla',
  path: '/isla',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizeRoute = PersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/builder': typeof BuilderRoute
  '/classroom': typeof ClassroomRoute
  '/core': typeof CoreRoute
  '/home': typeof HomeRoute
  '/isla': typeof IslaRoute
  '/missions': typeof MissionsRoute
  '/personalize': typeof PersonalizeRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/builder': typeof BuilderRoute
  '/classroom': typeof ClassroomRoute
  '/core': typeof CoreRoute
  '/home': typeof HomeRoute
  '/isla': typeof IslaRoute
  '/missions': typeof MissionsRoute
  '/personalize': typeof PersonalizeRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/builder': typeof BuilderRoute
  '/classroom': typeof ClassroomRoute
  '/core': typeof CoreRoute
  '/home': typeof HomeRoute
  '/isla': typeof IslaRoute
  '/missions': typeof MissionsRoute
  '/personalize': typeof PersonalizeRoute
  '/world': typeof WorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/builder'
    | '/classroom'
    | '/core'
    | '/home'
    | '/isla'
    | '/missions'
    | '/personalize'
    | '/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/builder'
    | '/classroom'
    | '/core'
    | '/home'
    | '/isla'
    | '/missions'
    | '/personalize'
    | '/world'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/builder'
    | '/classroom'
    | '/core'
    | '/home'
    | '/isla'
    | '/missions'
    | '/personalize'
    | '/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  BuilderRoute: typeof BuilderRoute
  ClassroomRoute: typeof ClassroomRoute
  CoreRoute: typeof CoreRoute
  HomeRoute: typeof HomeRoute
  IslaRoute: typeof IslaRoute
  MissionsRoute: typeof MissionsRoute
  PersonalizeRoute: typeof PersonalizeRoute
  WorldRoute: typeof WorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isla': {
      id: '/isla'
      path: '/isla'
      fullPath: '/isla'
      preLoaderRoute: typeof IslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalize': {
      id: '/personalize'
      path: '/personalize'
      fullPath: '/personalize'
      preLoaderRoute: typeof PersonalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  BuilderRoute: BuilderRoute,
  ClassroomRoute: ClassroomRoute,
  CoreRoute: CoreRoute,
  HomeRoute: HomeRoute,
  IslaRoute: IslaRoute,
  MissionsRoute: MissionsRoute,
  PersonalizeRoute: PersonalizeRoute,
  WorldRoute: WorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
